variables:
  REPO_NAME: aboutus-pc

stages:
  - imagebuild
  - deploy

image_dev:
  image: reg.redrock.team/base/redrock-imagebuilder:latest
  stage: imagebuild
  tags:
    - redrock-fe
  script:
    - docker build . -t reg.redrock.team/fe-dev-artifacts/${REPO_NAME}:${CI_COMMIT_SHA}
    - docker push reg.redrock.team/fe-dev-artifacts/${REPO_NAME}:${CI_COMMIT_SHA}
  only:
    - dev

image_prod:
  image: reg.redrock.team/base/redrock-imagebuilder:latest
  stage: imagebuild
  tags:
    - redrock-fe
  script:
    - docker build . -t reg.redrock.team/fe-prod-artifacts/${REPO_NAME}:${CI_COMMIT_SHA} -t ccr.ccs.tencentyun.com/redrock/fe-prod-artifacts:${REPO_NAME}-${CI_COMMIT_SHA}
    - docker push reg.redrock.team/fe-prod-artifacts/${REPO_NAME}:${CI_COMMIT_SHA}
    - docker push ccr.ccs.tencentyun.com/redrock/fe-prod-artifacts:${REPO_NAME}-${CI_COMMIT_SHA}
  only:
    - main

deploy_dev:
  image: reg.redrock.team/base/redrock-kubectl:latest
  stage: deploy
  tags:
    - redrock-fe
  variables:
    NAMESPACE: fe-dev
    VERSION: ${CI_COMMIT_SHA}
  script:
    - sed -i "s/_NAMESPACE_/${NAMESPACE}/" /deploy.yaml
    - sed -i "s/_VERSION_/${VERSION}/" /deploy.yaml
    - sed -i "s/_REPO_NAME_/${REPO_NAME}/" /deploy.yaml
    - kubectl apply -f /deploy.yaml
  environment:
    name: $REPO_NAME-dev
    url: https://$NAMESPACE.redrock.team/$REPO_NAME
  only:
    - dev

deploy_prod:
  image: reg.redrock.team/base/redrock-kubectl:latest
  stage: deploy
  tags:
    - redrock-fe
  variables:
    NAMESPACE: fe-prod
    VERSION: ${CI_COMMIT_SHA}
  script:
    - sed -i "s/_NAMESPACE_/${NAMESPACE}/" /deploy.yaml
    - sed -i "s/_VERSION_/${VERSION}/" /deploy.yaml
    - sed -i "s/_REPO_NAME_/${REPO_NAME}/" /deploy.yaml
    - kubectl apply -f /deploy.yaml
    - sed -i "s/_NAMESPACE_/${NAMESPACE}/" /deploy-tx.yaml
    - sed -i "s/_VERSION_/${VERSION}/" /deploy-tx.yaml
    - sed -i "s/_REPO_NAME_/${REPO_NAME}/" /deploy-tx.yaml
    - kubectl --kubeconfig=/config-tx apply -f /deploy-tx.yaml
    - sleep 10
    - curl -X POST https://be-prod.redrock.cqupt.edu.cn/cdn-cache-clean/$REPO_NAME
  environment:
    name: $REPO_NAME-prod
    url: https://$NAMESPACE.redrock.team/$REPO_NAME
  only:
    - main

